[package]
name        = "sql-experiments"
description = "Experiments generating SQL in Flix"
version     = "0.1.0"
flix        = "0.70.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/flix-pretty" = { version = "0.10.2", security = "unrestricted" }
"github:stephentetley/interop-json" = { version = "0.3.0", security = "unrestricted" }

